/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package javaapplication17;
import static java.lang.System.*;
import java.io.*;
import java.util.*;

class Resource implements AutoCloseable {
    private int i = 0;
    public void set(int i) {
        this.i = i;
    }
    @Override
    public void close() {
        String s = String.format("close %d", i);
        out.printf("%s%n", s);
        switch (i) {
            case -2:
            case -1:
            case 2:
                throw new NullPointerException(s);
        }
    }
    Resource(Object o) {
    }
}
/**
 *
 * try (...) {...}. no catch demo
    input file name:
    1. "a.txt" that doesn't exist under current dir. The following uses try() {} without any catch:
        try's () will not handle the FileNotFoundException in it! NO close() is called since the object
        fails to be instantiated!
run:
run:
a.txt
Exception in thread "main" java.io.FileNotFoundException: a.txt (系统找不到指定的文件。)
	at java.base/java.io.FileInputStream.open0(Native Method)
	at java.base/java.io.FileInputStream.open(FileInputStream.java:219)
	at java.base/java.io.FileInputStream.<init>(FileInputStream.java:157)
	at java.base/java.io.FileInputStream.<init>(FileInputStream.java:112)
	at javaapplication17.JavaApplication17.main(JavaApplication17.java:44)
        
    2. "build.xml" that does exist under current dir
        then 0 or 1 to see different results;
    the output of input 0:
run:
build.xml
try+, input:0
try-
close 0
main-
BUILD SUCCESSFUL (total time: 5 seconds)
        the output of input 1:
run:
build.xml
try+, input:1
before throw
close 1
Exception in thread "main" java.lang.RuntimeException: RE
	at javaapplication17.JavaApplication17.main(JavaApplication17.java:50)
	
        the output of 2, the NullPointerException generated by close is suppressed, at last only the Exception in {} block
        of try will be thrown.
run:
build.xml
try+, input:2
before throw
close 2
Exception in thread "main" java.lang.RuntimeException: RE
	at javaapplication17.JavaApplication17.main(JavaApplication17.java:50)
	Suppressed: java.lang.NullPointerException: close 2
		at javaapplication17.Resource.close(JavaApplication17.java:24)
		at javaapplication17.JavaApplication17.main(JavaApplication17.java:44)

        the output of -1:
run:
build.xml
try+, input:-1
try-
close -1
Exception in thread "main" java.lang.NullPointerException: close -1
	at javaapplication17.Resource.close(JavaApplication17.java:24)
	at javaapplication17.JavaApplication17.main(JavaApplication17.java:56)

        the output of -2:
run:
build.xml
try+, input:-2
before return
close -2
Exception in thread "main" java.lang.NullPointerException: close -2
	at javaapplication17.Resource.close(JavaApplication17.java:24)
	at javaapplication17.JavaApplication17.main(JavaApplication17.java:56)

       the output of -3:
run:
build.xml
try+, input:-3
before return
close -3
BUILD SUCCESSFUL (total time: 5 seconds)
        */
public class JavaApplication17 {

    /**
     * @param args the command line arguments
     */
    public static void main(String[] args) throws FileNotFoundException {
        // TODO code application logic here
        Scanner console = new Scanner(System.in);
        String file = console.next();

        try (Resource ms = new Resource(new FileInputStream(file))) {
            out.print("try+, input:");
            int i = console.nextInt();
            ms.set(i);
            if (i > 0) {
                out.println("before throw");
                throw new RuntimeException("RE");
            } else if (i <= -2) {
                out.println("before return");
                return;
            }
            out.println("try-");
        }
        /*
        catch (RuntimeException re) {
            out.println("re");
        }
        */
        out.println("main-");
    }
    
}
    